### ISSUE TITLE
Storj for go-storage

### ISSUE THREAD

**Issue by Prnyself** [beyondstorage/go-service-storj#1]
## Description

[Storj] is a decentralized cloud storage framework web platform, and this project will implement [go-storage]'s Storager interface for Storj, enabling users to manipulate data on the Storj service through a unified interface.

## Roadmap

- [ ] Choose a well maintained [Storj] library
- [ ] Implement all interface that Storager required
- [ ] Setup integration tests
- [ ] Add docs in [site](https://github.com/aos-dev/site)
- [ ] Add examples in [example](https://github.com/aos-dev/go-storage-example)

[Storj]: https://www.storj.io/
[go-storage]: https://github.com/aos-dev/go-storage

**Comment by Xuanwo** [comment]
@OAkaLala is responsible for this issue.

**Comment by Xuanwo** [comment]
@OAkaLala, hello, 8/15 is the deadline for mid-term submit. How is the progress now?

**Comment by KaiyuanLiu0** [comment]
@Xuanwo Sorry for my late response. I am currently work in progress on this project and I'll have a pull request soon.
